export const orders = [
  {
    order_id: "M-147",
    customer_name: "Валентина",
    order_time: "09:20",
    order_place: "На вынос",
    order_status: "Новый",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
      { dish_name: "Другое блюдо", quantity: "1" },
    ],
  },
  {
    order_id: "M-148",
    customer_name: "Валентина",
    order_time: "10:20",
    order_place: "На вынос",
    order_status: "В процессе",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
      { dish_name: "Другое блюдо", quantity: "1" },
      { dish_name: "Еще одно блюдо", quantity: "1" },
      { dish_name: "Еще одно блюдо 2", quantity: "1" },
    ],
  },
  {
    order_id: "M-149",
    customer_name: "Валентина",
    order_time: "11:20",
    order_place: "На вынос",
    order_status: "Новый",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
    ],
  },
  {
    order_id: "M-150",
    customer_name: "Валентина",
    order_time: "12:20",
    order_place: "На вынос",
    order_status: "Готово",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
      { dish_name: "Другое блюдо", quantity: "1" },
      { dish_name: "Еще одно блюдо", quantity: "1" },
    ],
  },
  {
    order_id: "M-151",
    customer_name: "Валентина",
    order_time: "13:20",
    order_place: "На вынос",
    order_status: "Отменено",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
      { dish_name: "Другое блюдо", quantity: "1" },
      { dish_name: "Еще одно блюдо", quantity: "1" },
    ],
  },
  {
    order_id: "M-152",
    customer_name: "Валентина",
    order_time: "14:20",
    order_place: "На вынос",
    order_status: "Новый",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
      { dish_name: "Другое блюдо", quantity: "1" },
    ],
  },
  {
    order_id: "M-153",
    customer_name: "Валентина",
    order_time: "15:20",
    order_place: "На вынос",
    order_status: "Новый",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
      { dish_name: "Другое блюдо", quantity: "1" },
      { dish_name: "Еще одно блюдо", quantity: "1" },
      { dish_name: "Еще одно блюдо 2", quantity: "1" },
    ],
  },
  {
    order_id: "M-154",
    customer_name: "Валентина",
    order_time: "16:20",
    order_place: "На вынос",
    order_status: "Новый",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
    ],
  },
  {
    order_id: "M-55",
    customer_name: "Валентина",
    order_time: "17:20",
    order_place: "В заведении",
    table_id:"10",
    order_status: "Новый",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
      { dish_name: "Другое блюдо", quantity: "1" },
      { dish_name: "Еще одно блюдо", quantity: "1" },
    ],
  },
  {
    order_id: "M-56",
    customer_name: "Валентина",
    order_time: "18:20",
    order_place: "В заведени",
    table_id:"9",
    order_status: "Новый",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
      { dish_name: "Другое блюдо", quantity: "1" },
      { dish_name: "Еще одно блюдо", quantity: "1" },
    ],
  },
  {
    order_id: "M-57",
    customer_name: "Валентина",
    order_time: "19:20",
    order_place: "В заведени",
    table_id:"8",
    order_status: "Новый",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
      { dish_name: "Другое блюдо", quantity: "1" },
    ],
  },
  {
    order_id: "M-58",
    customer_name: "Валентина",
    order_time: "20:20",
    order_place: "В заведении",
    table_id:"7",
    order_status: "Завершено",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
      { dish_name: "Другое блюдо", quantity: "1" },
      { dish_name: "Еще одно блюдо", quantity: "1" },
      { dish_name: "Еще одно блюдо 2", quantity: "1" },
    ],
  },
  {
    order_id: "M-59",
    customer_name: "Валентина",
    order_time: "21:20",
    order_place: "В заведении",
    table_id:"6",
    order_status: "Завершено",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
    ],
  },
  {
    order_id: "M-60",
    customer_name: "Валентина",
    order_time: "22:20",
    order_place: "В заведении",
    table_id:"5",
    order_status: "Новый",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
      { dish_name: "Другое блюдо", quantity: "1" },
      { dish_name: "Еще одно блюдо", quantity: "1" },
    ],
  },
  {
    order_id: "M-61",
    customer_name: "Валентина",
    order_time: "23:20",
    order_place: "В заведении",
    table_id:"4",
    order_status: "В процессе",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
      { dish_name: "Другое блюдо", quantity: "1" },
      { dish_name: "Еще одно блюдо", quantity: "1" },
    ],
  },
];

export const orderNotifications = [
  {
    order_id: "M-57",
    customer_name: "Валентина",
    order_time: "19:20",
    order_place: "В заведени",
    table_id:"8",
    order_status: "Новый",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Латте", quantity: "1" },
      { dish_name: "Чизкейк", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
    ],
  },
  {
    order_id: "M-147",
    customer_name: "Валентина",
    order_time: "09:20",
    order_place: "На вынос",
    order_status: "Новый",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Латте", quantity: "1" },
    ],
  },
  {
    order_id: "M-56",
    customer_name: "Валентина",
    order_time: "18:20",
    order_place: "В заведени",
    table_id:"9",
    order_status: "Новый",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
      { dish_name: "Другое блюдо", quantity: "1" },
      { dish_name: "Еще одно блюдо", quantity: "1" },
    ],
  },
  {
    order_id: "M-148",
    customer_name: "Валентина",
    order_time: "10:20",
    order_place: "На вынос",
    order_status: "В процессе",
    order_items: [
      { dish_name: "Капучино", quantity: "1" },
      { dish_name: "Багровый закат", quantity: "1" },
      { dish_name: "Мохито Клубничный", quantity: "1" },
      { dish_name: "Другое блюдо", quantity: "1" },
      { dish_name: "Еще одно блюдо", quantity: "1" },
      { dish_name: "Еще одно блюдо 2", quantity: "1" },
    ],
  },
]

export const orderStatus = [
  { color: "#FF5151", status: "новый", title: "Новый" },
  { color: "#F9B70F", status: "в_процессе", title: "В процессе"  },
  { color: "#37D400", status: "готово", title: "Готово"  },
  { color: "#171717", status: "отменено", title: "Отменено"  },
  { color: "#717171", status: "оплачено", title: "Завершено"  },
];
