export const orders = [
    {
      order_id: "M-47", 
      customer_name: "Валентина",
      order_place: 'На вынос',
      order_status: "Новый",
      order_items: [
        { dish_name: "Капучино", quantity: "x1" },
        { dish_name: "Багровый закат", quantity: "x1" },
        { dish_name: "Мохито Клубничный", quantity: "x1" },
        { dish_name: "Другое блюдо", quantity: "x1" },
      ],
    },
    {
      order_id: "M-48", 
      customer_name: "Валентина",
       order_place: 'На вынос',
      order_status: "В процессе",
      order_items: [
        { dish_name: "Капучино", quantity: "x1" },
        { dish_name: "Багровый закат", quantity: "x1" },
        { dish_name: "Мохито Клубничный", quantity: "x1" },
        { dish_name: "Другое блюдо", quantity: "x1" },
        { dish_name: "Еще одно блюдо", quantity: "x1" },
        { dish_name: "Еще одно блюдо 2", quantity: "x1" },
      ],
    },
    {
      order_id: "M-49", 
      customer_name: "Валентина",
       order_place: 'На вынос',
      order_status: "Новый",
      order_items: [
        { dish_name: "Капучино", quantity: "x1" },
        { dish_name: "Багровый закат", quantity: "x1" },
        { dish_name: "Мохито Клубничный", quantity: "x1" }
      ],
    },
    {
      order_id: "M-50", 
      customer_name: "Валентина",
       order_place: 'На вынос',
      order_status: "Готово",
      order_items: [
        { dish_name: "Капучино", quantity: "x1" },
        { dish_name: "Багровый закат", quantity: "x1" },
        { dish_name: "Мохито Клубничный", quantity: "x1" },
        { dish_name: "Другое блюдо", quantity: "x1" },
        { dish_name: "Еще одно блюдо", quantity: "x1" },
      ],
    },
    {
      order_id: "M-51", 
      customer_name: "Валентина",
       order_place: 'На вынос',
      order_status: "Отменено",
      order_items: [
        { dish_name: "Капучино", quantity: "x1" },
        { dish_name: "Багровый закат", quantity: "x1" },
        { dish_name: "Мохито Клубничный", quantity: "x1" },
        { dish_name: "Другое блюдо", quantity: "x1" },
        { dish_name: "Еще одно блюдо", quantity: "x1" },
      ],
    },
    {
      order_id: "M-52", 
      customer_name: "Валентина",
       order_place: 'На вынос',
      order_status: "Новый",
      order_items: [
        { dish_name: "Капучино", quantity: "x1" },
        { dish_name: "Багровый закат", quantity: "x1" },
        { dish_name: "Мохито Клубничный", quantity: "x1" },
        { dish_name: "Другое блюдо", quantity: "x1" },
      ],
    },
    {
      order_id: "M-53", 
      customer_name: "Валентина",
       order_place: 'На вынос',
      order_status: "Новый",
      order_items: [
        { dish_name: "Капучино", quantity: "x1" },
        { dish_name: "Багровый закат", quantity: "x1" },
        { dish_name: "Мохито Клубничный", quantity: "x1" },
        { dish_name: "Другое блюдо", quantity: "x1" },
        { dish_name: "Еще одно блюдо", quantity: "x1" },
        { dish_name: "Еще одно блюдо 2", quantity: "x1" },
      ],
    },
    {
      order_id: "M-54", 
      customer_name: "Валентина",
       order_place: 'На вынос',
      order_status: "Новый",
      order_items: [
        { dish_name: "Капучино", quantity: "x1" },
        { dish_name: "Багровый закат", quantity: "x1" },
        { dish_name: "Мохито Клубничный", quantity: "x1" }
      ],
    },
    {
      order_id: "M-55", 
      customer_name: "Валентина",
       order_place: 'В заведении',
      order_status: "Новый",
      order_items: [
        { dish_name: "Капучино", quantity: "x1" },
        { dish_name: "Багровый закат", quantity: "x1" },
        { dish_name: "Мохито Клубничный", quantity: "x1" },
        { dish_name: "Другое блюдо", quantity: "x1" },
        { dish_name: "Еще одно блюдо", quantity: "x1" },
      ],
    },
    {
      order_id: "M-56", 
      customer_name: "Валентина",
       order_place: 'Готово',
      order_status: "Новый",
      order_items: [
        { dish_name: "Капучино", quantity: "x1" },
        { dish_name: "Багровый закат", quantity: "x1" },
        { dish_name: "Мохито Клубничный", quantity: "x1" },
        { dish_name: "Другое блюдо", quantity: "x1" },
        { dish_name: "Еще одно блюдо", quantity: "x1" },
      ],
    },
    {
      order_id: "M-57", 
      customer_name: "Валентина",
       order_place: 'Завершено',
      order_status: "Новый",
      order_items: [
        { dish_name: "Капучино", quantity: "x1" },
        { dish_name: "Багровый закат", quantity: "x1" },
        { dish_name: "Мохито Клубничный", quantity: "x1" },
        { dish_name: "Другое блюдо", quantity: "x1" },
      ],
    },
    {
      order_id: "M-58", 
      customer_name: "Валентина",
       order_place: 'В заведении',
      order_status: "Завершено",
      order_items: [
        { dish_name: "Капучино", quantity: "x1" },
        { dish_name: "Багровый закат", quantity: "x1" },
        { dish_name: "Мохито Клубничный", quantity: "x1" },
        { dish_name: "Другое блюдо", quantity: "x1" },
        { dish_name: "Еще одно блюдо", quantity: "x1" },
        { dish_name: "Еще одно блюдо 2", quantity: "x1" },
      ],
    },
    {
      order_id: "M-59", 
      customer_name: "Валентина",
       order_place: 'В заведении',
      order_status: "Завершено",
      order_items: [
        { dish_name: "Капучино", quantity: "x1" },
        { dish_name: "Багровый закат", quantity: "x1" },
        { dish_name: "Мохито Клубничный", quantity: "x1" }
      ],
    },
    {
      order_id: "M-60", 
      customer_name: "Валентина",
       order_place: 'В заведении',
      order_status: "Новый",
      order_items: [
        { dish_name: "Капучино", quantity: "x1" },
        { dish_name: "Багровый закат", quantity: "x1" },
        { dish_name: "Мохито Клубничный", quantity: "x1" },
        { dish_name: "Другое блюдо", quantity: "x1" },
        { dish_name: "Еще одно блюдо", quantity: "x1" },
      ],
    },
    {
      order_id: "M-61", 
      customer_name: "Валентина",
       order_place: 'В заведении',
      order_status: "В процессе",
      order_items: [
        { dish_name: "Капучино", quantity: "x1" },
        { dish_name: "Багровый закат", quantity: "x1" },
        { dish_name: "Мохито Клубничный", quantity: "x1" },
        { dish_name: "Другое блюдо", quantity: "x1" },
        { dish_name: "Еще одно блюдо", quantity: "x1" },
      ],
    },
  ];

export const orderStatus = [
    { color: "#FF5151", status: "Новый" },
    { color: "#F9B70F", status: "В процессе" },
    { color: "#37D400", status: "Готово" },
    { color: "#171717", status: "Отменено" },
    { color: "#717171", status: "Завершено" },
  ];